--- #my playbook for handlers
- hosts: demo
  user: ansible
  become: yes
  tasks:
    - name: install httpd server on centos
      action: yum name=httpd state=installed
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
