--- #my loop playbook for testing perpose
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: add list of users in my nodes
      user: name="{{item}}" state=present
      with_items:
        - sachinraj
        - bhupendra
        - rajat
        - vasco_D_gama #if any user has space in user name then user not created by ansible playbook if u want to create user with space then you chng space form  "_" this under score.
